#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

cd "${0%/*}"

mkdir -p ./fonts

#
# Download then verify the zips
#
curl -Lo ./fonts/latin-modern.zip --skip-existing \
  'https://www.gust.org.pl/projects/e-foundry/latin-modern/download/lm2.004otf.zip'
curl -Lo ./fonts/bareon-batang.zip --skip-existing \
  --referer 'https://copyright.keris.or.kr/wft/fntDwnldView' \
  -d 'fntGrpId=GFT202301120000000000002&fntFileId=FTF202312080000000000070' \
  'https://copyright.keris.or.kr/cmm/fntDwnldById'
b2sum --quiet -c <<'EOF'
87472bdd53899c1dfec8f4b8491fabc7878b1f8c1e72424ae0edf79c7f22fd873f6c3e650d3201dfa4481185dffa5960202919a621fd056947540d215eb20bec fonts/bareon-batang.zip
448233fb23437a08997d8cb6d2600709223ce8dc2fbce949652b47071450a7a0a0915bcfa59bb88b5e52e5fdb6021c93c38891fa05f106fa299a61bd3cbefd5e fonts/latin-modern.zip
EOF

#
# Unzip
#
unzip -qo ./fonts/latin-modern.zip -d ./fonts
unzip -qo ./fonts/bareon-batang.zip '*.otf' -d ./fonts

#
# Build all
#
typst compile --font-path fonts *.typ
