#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

help () {
  cat <<-'EOF'
aws-mfa
MFA 인증이 완료된 AWS CLI 액세스 토큰을 얻어와주는 유틸리티입니다.

Usage:
  aws-mfa [<source-profile>] [<destination-profile>] [<token-arn>]
  aws-mfa [-h|--help]

  <source-profile>        이 프로필을 사용해 MFA 로그인을 합니다. (기본값: "default")
  <destination-profile>   MFA 로그인 결과를 이 프로필에 저장합니다. (기본값: "<source-profile>-mfa")
  <token-arn>             MFA 인증을 할 virtual MFA device의 ARN입니다. (기본값: 첫번째 virtual MFA device의 ARN)
  -h, --help              이 도움말을 표시합니다

Example:
  aws-mfa
  aws-mfa myprofile
  aws-mfa myprofile mfa-myprofile
  aws-mfa myprofile mfa-myprofile arn:aws:iam::012345678901:mfa/simnalamburt
EOF
}

if (( $# > 3 )); then
  help
  exit 1
fi

if [[ "${1:-}" == '-h' || "${1:-}" == '--help' ]]; then
  help
  exit
fi


#
# 종속성 확인
#
for DEP in python3 aws; do
  if ! command -v "$DEP" >/dev/null 2>&1; then
    ABSENT=$DEP
    break
  fi
done
if [[ -n ${ABSENT+x} ]]; then
  echo "프로그램 '$ABSENT'가 설치되어있지 않습니다."
  exit 1
fi


unset AWS_PROFILE
unset AWS_DEFAULT_PROFILE


#
# Parse ARGV
#
PROFILE_SRC="${1:-default}"
PROFILE_DST="${2:-"${PROFILE_SRC}-mfa"}"
SERIAL_NUMBER="${3:-"$(aws iam list-mfa-devices \
  --query 'MFADevices[].SerialNumber | [0]' \
  --profile "${PROFILE_SRC}" \
  --output text)"}"


#
# 기존 토큰 만료 여부 확인
#
EXPIRATION=$(aws configure get "profile.${PROFILE_DST}.expiration" || true)
# 새 토큰을 발급받아야 하는 상황에서만 1을 반환하는 스크립트
if python3 <<-EOF; then echo '이미 유효한 토큰이 발급되어있어 아무것도 하지 않았습니다.' && exit; fi
from sys import exit
from datetime import datetime, timezone

expr = '${EXPIRATION}'
if not expr:
    exit(1)
time = (
    datetime.strptime(expr, '%Y-%m-%dT%H:%M:%S%z')
    if expr[-1] != 'Z' else
    datetime.strptime(expr, '%Y-%m-%dT%H:%M:%SZ').replace(tzinfo=timezone.utc)
)
exit(1 if time <= datetime.now(timezone.utc) else 0)
EOF


#
# OTP 코드 입력받음
#
read -p 'AWS 토큰 숫자 여섯자리를 입력하세요: ' -r TOKEN_CODE


#
# 발급받은 액세스토큰 저장
#
JSON=$(
  aws sts get-session-token \
    --duration-seconds 129600 \
    --serial-number "${SERIAL_NUMBER}" \
    --token-code "${TOKEN_CODE}" \
    --profile "${PROFILE_SRC}"
)
aws configure set "profile.${PROFILE_DST}.aws_access_key_id" \
  "$(<<< "$JSON" python3 -c 'import sys,json;print(json.loads(sys.stdin.read())["Credentials"]["AccessKeyId"])')" \
  --profile "${PROFILE_SRC}"
aws configure set "profile.${PROFILE_DST}.aws_secret_access_key" \
  "$(<<< "$JSON" python3 -c 'import sys,json;print(json.loads(sys.stdin.read())["Credentials"]["SecretAccessKey"])')" \
  --profile "${PROFILE_SRC}"
aws configure set "profile.${PROFILE_DST}.aws_session_token" \
  "$(<<< "$JSON" python3 -c 'import sys,json;print(json.loads(sys.stdin.read())["Credentials"]["SessionToken"])')" \
  --profile "${PROFILE_SRC}"
aws configure set "profile.${PROFILE_DST}.expiration" \
  "$(<<< "$JSON" python3 -c 'import sys,json;print(json.loads(sys.stdin.read())["Credentials"]["Expiration"])')" \
  --profile "${PROFILE_SRC}"
echo '토큰 갱신이 완료되었습니다.'
