#!/bin/bash

# Check if there are text files without LF at EOF or with trailing whitespace,
# using only git. If git misidentifies binary files as text files, correct it
# with .gitattributes.

set -euo pipefail; IFS=$'\n\t'

EXIT_CODE=0
if git -P grep -IPl '[^\n]\z'; then
  echo -e '⚠️ Text files without LF at EOF found\n'
  EXIT_CODE=1
fi

if git -P grep -IPn '[[:space:]]+$'; then
  echo -e '⚠️ Trailing whitespace found\n'
  EXIT_CODE=1
fi

exit "${EXIT_CODE}"
