#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

DIRNAME="blabla"

convert() {
  local RUN=$1
  local RESULT EXT

  for FILE in $(find "$DIRNAME" -type f); do
    RESULT=$(xxd -p -l 4 "$FILE")

    if [ "$RESULT" = "ffd8ffe0" ]; then
      EXT="jpg"
    elif [ "$RESULT" = "ffd8ffe1" ]; then
      EXT="jpg"
    elif [ "$RESULT" = "89504e47" ]; then
      EXT="png"
    else
      printf '알수없는 형식의 파일을 만났다!\n\n%s\n\n' "$FILE"
      xxd -l 32 "$FILE"
      exit 1
    fi;

    if [ "$RUN" = "--run" ]; then
      mv "$FILE" "$FILE.$EXT"
    else
      printf 'mv %s %s.%s\n' "$FILE" "$FILE" "$EXT"
    fi
  done
}

convert

read -r -p "파일 이름을 바꾸시겠어요? [y/N] " RESPONSE
case "$RESPONSE" in
  [yY][eE][sS]|[yY]);;
  *) exit 1;;
esac

convert --run
