#!/bin/bash

# fzf로 원하는 파일 내용을 검색한 뒤, vim으로 열어주는 프로그램.
# 실시간 미리보기와 다중선택도 지원한다.
#
# Requirements:
#   rg
#   fzf
#   bat (optional)
#
# Special thanks to @xnuk https://github.com/xnuk/

set -euo pipefail; IFS=$'\n\t'

PREVIEW='
  LINE={2}
  LINE=${LINE%?}
  BEGIN=$((LINE > FZF_PREVIEW_LINES/2 ? LINE - FZF_PREVIEW_LINES/2 + 1 : 1))
  END=$((BEGIN + FZF_PREVIEW_LINES - 1))
'

# bat이 없을경우 sed를 bat 대신 사용한다.
if [ -x "$(command -v bat)" ]; then
  PREVIEW=$PREVIEW'; bat -ppH$LINE --color=always -r$BEGIN:$END {1}'
else
  PREVIEW=$PREVIEW'; sed -n "${BEGIN},${END}p" {1}'
fi

ARGS=$(
  rg --no-config -nH0 --color=always '\A' -r'🌏🔥🐸🐹😂😍😘' |
  fzf -m -d'\0|🌏🔥🐸🐹😂😍😘' -n'2..' --with-nth='1,3..' \
    --ansi --color=border:0 --layout=reverse --preview="${PREVIEW}" |
  rg --no-config -a '\A(.*)\x00(.*):🌏🔥🐸🐹😂😍😘(.*)$' -r'+"tabnew +$2 $1"'
)

eval exec vim ${ARGS} +1tabclose
