#!/bin/bash

# fzf로 원하는 파일 내용을 검색한 뒤, vim으로 열어주는 프로그램.
# 실시간 미리보기와 다중선택도 지원한다.
#
# Special thanks to @xnuk https://github.com/xnuk/

set -euo pipefail; IFS=$'\n\t'

ARGS=$(
  rg --no-config -nH0 --color=always '\A' -r'🌏🔥🐸🐹😂😍😘' |
  fzf -m -d'\0|🌏🔥🐸🐹😂😍😘' -n'2..' --with-nth='1,3..' \
    --ansi --color=border:0 --layout=reverse --preview='
      LINE={2}; LINE=${LINE%?};
      BEGIN=$((LINE > FZF_PREVIEW_LINES/2 ? LINE - FZF_PREVIEW_LINES/2 : 0))
      END=$((BEGIN + FZF_PREVIEW_LINES - 1))
      bat -ppH$LINE --color=always -r$BEGIN:$END {1}
    ' |
  rg --no-config -a '\A(.*)\x00(.*):🌏🔥🐸🐹😂😍😘(.*)$' -r'+"tabnew +$2 $1"'
)

eval exec vim ${ARGS} +1tabclose
