#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

__get_ms_time="$(date +%s%N)"
get_ms() {
  local new_time
  new_time="$(date +%s%N)"
  echo "$(( new_time - __get_ms_time ))ns"
  __get_ms_time="$new_time"
}

for _ in {1..300000}; do
  :
done

get_ms

for _ in {1..500000}; do
  :
done

get_ms
